name: Rust CI

on:
  push:
    branches:
      - main  # 這裡可以替換成你的主要分支名稱
      - hw1-p
      - hw1-f
  pull_request:
    branches:
      - main  # 當有 pull request 到主分支時也會觸發 CI
      - hw1-p
      - hw1-f

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 上執行
    steps:
      - name: Check out the code
        uses: actions/checkout@v3  # 檢出程式碼

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # 使用 stable 版的 Rust
          override: true

      - name: Install dependencies
        run: |
          cargo fetch  # 確保所有依賴都被下載

      - name: Run tests
        run: |
          cargo test --verbose  # 執行測試，並顯示詳細訊息
          
      - name: Cache target directory
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
